inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - payday.rb

Metrics/AbcSize:
  Exclude:
    - lib/printer.rb
    - lib/plots/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15
  Exclude:
    - lib/plots/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
