inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - payday.rb 

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
