require './config/application'

Category.find_or_create_by(name: 'bonus')
Category.find_or_create_by(name: 'codzienne')
Category.find_or_create_by(name: 'transport')
Category.find_or_create_by(name: 'rozrywka')
Category.find_or_create_by(name: 'miasto')
Category.find_or_create_by(name: 'firma')
Category.find_or_create_by(name: 'zakupy')
Category.find_or_create_by(name: 'rachunki')
Category.find_or_create_by(name: 'czynsz')
Category.find_or_create_by(name: 'wynagrodzenie')
Category.find_or_create_by(name: 'inne')
Category.find_or_create_by(name: 'zus')
Category.find_or_create_by(name: 'wyjazdy')
Category.find_or_create_by(name: 'oszczednosci')
